services:
  jmeter:
    build:
      context: ./benchmark/jmeter
      dockerfile: Dockerfile
    networks:
      - nw
    volumes:
      - ./benchmark/jmeter/plan.jmx:/plan.jmx
    entrypoint: /bin/bash
    tty: true
    deploy:
      resources:
        limits:
          cpus: 12.0
          memory: 64g
        reservations: # Guarantee resources
          cpus: 12.0
          memory: 64g
    mem_limit: 64g
    memswap_limit: 64g # Disable swap
    cpuset: "4-15" # 12 cores

  db:
    image: postgres:17.4
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./benchmark/pagila/pagila-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./benchmark/pagila/pagila-data.sql:/docker-entrypoint-initdb.d/02-data.sql
    networks:
      - nw
    deploy:
      resources:
        limits:
          cpus: 4.0
          memory: 16g
        reservations: # Guarantee resources
          cpus: 4.0
          memory: 16g
    mem_limit: 16g
    memswap_limit: 16g # Disable swap
    cpuset: "16-19" # 4 cores

  vapor:
    build:
      context: ./vapor
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - nw
    deploy:
      resources:
        limits:
          cpus: 4.0
          memory: 16g
        reservations: # Guarantee resources
          cpus: 4.0
          memory: 16g
    mem_limit: 16g
    memswap_limit: 16g # Disable swap
    cpuset: "20-23" # 4 cores
    volumes:
      - ./server_resources/lipsum.txt:/tmp/lipsum.txt

  ktor:
    build:
      context: ./ktor
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - nw
    deploy:
      resources:
        limits:
          cpus: 4.0
          memory: 16g
        reservations: # Guarantee resources
          cpus: 4.0
          memory: 16g
    mem_limit: 16g
    memswap_limit: 16g # Disable swap
    cpuset: "20-23" # 4 cores
    volumes:
      - ./server_resources/lipsum.txt:/tmp/lipsum.txt

  express:
    build:
      context: ./express
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - nw
    deploy:
      resources:
        limits:
          cpus: 4.0
          memory: 16g
        reservations: # Guarantee resources
          cpus: 4.0
          memory: 16g
    mem_limit: 16g
    memswap_limit: 16g # Disable swap
    cpuset: "20-23" # 4 cores
    volumes:
      - ./server_resources/lipsum.txt:/tmp/lipsum.txt

networks:
  nw:
    name: nw
    external: false
