services:
  jmeter:
    build:
      context: ./benchmark/jmeter
      dockerfile: Dockerfile
    environment:
      JVM_ARGS: "-Xms16g -Xmx32g"
    networks:
      - nw
    volumes:
      - ./benchmark/jmeter/plan.jmx:/plan.jmx
      - ./benchmark/results:/results
    deploy:
      resources:
        limits:
          cpus: 8.0
          memory: 64g
        reservations: # Guarantee resources
          cpus: 8.0
          memory: 64g
    mem_limit: 64g
    memswap_limit: 64g # Disable swap
    cpuset: "4-11" # 8 cores

  db:
    image: postgres:17.4
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./benchmark/pagila/pagila-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./benchmark/pagila/pagila-data.sql:/docker-entrypoint-initdb.d/02-data.sql
    networks:
      - nw
    deploy:
      resources:
        limits:
          cpus: 8.0
          memory: 32g
        reservations: # Guarantee resources
          cpus: 8.0
          memory: 32g
    mem_limit: 32g
    memswap_limit: 32g # Disable swap
    cpuset: "12-19" # 8 cores

  vapor:
    build:
      context: ./vapor
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - nw
    deploy:
      resources:
        limits:
          cpus: 4.0
          memory: 8g
        reservations: # Guarantee resources
          cpus: 4.0
          memory: 8g
    mem_limit: 8g
    memswap_limit: 8g # Disable swap
    cpuset: "20-23" # 4 cores
    volumes:
      - ./server_resources/lipsum.txt:/tmp/lipsum.txt

  ktor:
    build:
      context: ./ktor
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - nw
    deploy:
      resources:
        limits:
          cpus: 4.0
          memory: 8g
        reservations: # Guarantee resources
          cpus: 4.0
          memory: 8g
    mem_limit: 8g
    memswap_limit: 8g # Disable swap
    cpuset: "20-23" # 4 cores
    volumes:
      - ./server_resources/lipsum.txt:/tmp/lipsum.txt

  express:
    build:
      context: ./express
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - nw
    deploy:
      resources:
        limits:
          cpus: 4.0
          memory: 8g
        reservations: # Guarantee resources
          cpus: 4.0
          memory: 8g
    mem_limit: 8g
    memswap_limit: 8g # Disable swap
    cpuset: "20-23" # 4 cores
    volumes:
      - ./server_resources/lipsum.txt:/tmp/lipsum.txt

networks:
  nw:
    name: nw
    external: false
