services:
  db:
    image: postgres:17.4
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./pagila/pagila-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./pagila/pagila-data.sql:/docker-entrypoint-initdb.d/02-data.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080
